server:
  port: 8888
spring:
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-mm-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding:
      charset: UTF-8
  devtools:
    livereload:
      enabled: true
  redis:
    port: 6379
    database: 0
    host: localhost
    password: 123456
    jedis:
      pool:
        max-wait: 1000ms
        max-idle: 10
        min-idle: 10
        max-active: 10
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/draw_lottery?useSSL=false&useUnicode=true&amp;characterEncoding=UTF8

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
logging:
  level:
    ROOT: info
    com:
      itsu:
        spbmanagevue:
          dao: trace
